# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6ce3a323eec826b371a1907709c7454343426037a8aa633ccdb97b857b37b81096a7f73a76d1a913255ad66700bc38e6ec50f2a9bdab63f78e0f8c52056bbdd2

test:
  secret_key_base: 91bd9006d9cef6c53f22c2b55ff832d1769d027927e7d400d037904327633c519dfde47081b8e51caf25dac140447d63c50af28a4d984e67169219adef17d584

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
